name: tagkiri

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'タグ名（x.y.zの形式）'

jobs:
  tagkiri:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: extract version
        id: extract-version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          major=$(echo $VERSION | cut -d. -f1)
          minor=$(echo $VERSION | cut -d. -f2)
          patch=$(echo $VERSION | cut -d. -f3)
          echo "major=$major" >> $GITHUB_OUTPUT
          echo "minor=$minor" >> $GITHUB_OUTPUT
          echo "patch=$patch" >> $GITHUB_OUTPUT

      - name: switch to stable branch
        env:
          MAJOR: ${{ steps.extract-version.outputs.major }}
          MINOR: ${{ steps.extract-version.outputs.minor }}
        run: |
          branch_name="stable/$MAJOR.$MINOR"
          git fetch origin $branch_name
          git checkout $branch_name

      - name: Fetch tags
        run: |
          git fetch --tags

      - name: Get prev version
        id: prev-version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          PREV_VERSION=$(git tag --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | awk -v version="$VERSION" '$0 < version' | tail -1)
          echo "prev_version=$PREV_VERSION" >> $GITHUB_OUTPUT

          HEAD=$(git rev-parse HEAD)
          echo "head=$HEAD" >> $GITHUB_OUTPUT

      - name: Create new milestone
        id: create-new-milestone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ inputs.version }}
          OWNER: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.repository }}
        run: |
          # TODO: マイルストーンの存在確認
          gh milestone create "$NEW_VERSION" --owner "$OWNER" --repo "$REPOSITORY"
          milestone_number=$(gh milestone list --owner "$OWNER" --repo "$REPOSITORY" --json number --jq '.[0].number')
          echo "milestone_number=$milestone_number" >> $GITHUB_OUTPUT

      - name: Get all commits between base and head, and find associated PRs
        if: steps.prev-version.outputs.prev_version != ''
        uses: actions/github-script@v7
        env:
          PREV_VERSION: ${{ steps.prev-version.outputs.prev_version }}
          HEAD: ${{ steps.prev-version.outputs.head }}
          MAJOR_VERSION: ${{ steps.extract-version.outputs.major }}
          MINOR_VERSION: ${{ steps.extract-version.outputs.minor }}
          NEW_VERSION: ${{ inputs.version }}
          NEW_MILESTONE_NUMBER: ${{ steps.create-new-milestone.outputs.milestone_number }}
        with:
          script: |
            const base = process.env.PREV_VERSION;
            const head = process.env.HEAD;
            const majorVersion = process.env.MAJOR_VERSION;
            const minorVersion = process.env.MINOR_VERSION;
            const newVersion = process.env.NEW_VERSION;
            const newMilestoneNumber = process.env.NEW_MILESTONE_NUMBER;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const compare = await github.rest.repos.compareCommitsWithBasehead({
              owner,
              repo,
              basehead: `${base}...${head}`,
            });

            let page = 1;
            let allCommits = [];
            let per_page = 100;
            let hasNext = true;

            while (hasNext) {
              const commitsResp = await github.rest.repos.listCommits({
                owner,
                repo,
                sha: head,
                since: compare.data.base_commit.commit.author.date,
                per_page,
                page,
              });
              if (commitsResp.data.length === 0) {
                hasNext = false;
              } else {
                allCommits = allCommits.concat(commitsResp.data);
                page++;
                if (commitsResp.data.length < per_page) {
                  hasNext = false;
                }
              }
            }

            // base以降のコミットだけに絞る
            let filteredCommits = [];
            for (const commit of allCommits) {
              if (commit.sha === compare.data.base_commit.sha) break;
              filteredCommits.push(commit);
            }
            filteredCommits = filteredCommits.reverse();

            console.log(`取得したコミット数: ${filteredCommits.length}`);

            const prs = filteredCommits.map(async (commit) => {
              const prNumber = commit.commit.message.split('\n')[0].match(/\(#(\d+)\)$/)?.[1];
              if (!prNumber) return null;

              const pr = await github.rest.pulls.get({
                owner,
                repo,
                pull_number: prNumber,
              });
              const milestoneTitle = pr.data.milestone?.title;

              // PRに設定されたマイルストーンとバージョンが一致する場合、PRのマイルストーンを新しいマイルストーンに変更する
              if (milestoneTitle === `${majorVersion}.${minorVersion}.x`) {
                return github.rest.issues.update({
                  owner,
                  repo,
                  issue_number: prNumber,
                  milestone_number: newMilestoneNumber,
                });
              }

              // PRにコメントを追加する
              return github.rest.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: `${newVersion}にも適用`,
              });
            });
            await Promise.all(prs);


            // for (const commit of filteredCommits) {
            //   const prs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
            //     owner,
            //     repo,
            //     commit_sha: commit.sha,
            //   });
            //   if (prs.data.length > 0) {
            //     console.log(`コミット: ${commit.sha} (${commit.commit.message.split('\n')[0]})`);
            //     for (const pr of prs.data) {
            //       console.log(`  PR: #${pr.number} ${pr.title}`);
            //     }
            //   } else {
            //     console.log(`コミット: ${commit.sha} (${commit.commit.message.split('\n')[0]})`);
            //     console.log(`  PR: なし`);
            //   }
            // }

concurrency:
  group: ${{ github.workflow }}-${{ inputs.version }}
  cancel-in-progress: true
